name: Build Agents

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Agent
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Build
        run: |
          mkdir -p apps/agent/dist/${{ matrix.goos }}-${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
            go build -o apps/agent/dist/${{ matrix.goos }}-${{ matrix.goarch }}/agent \
            ./apps/agent/cmd/agent

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-${{ matrix.goos }}-${{ matrix.goarch }}
          path: apps/agent/dist/${{ matrix.goos }}-${{ matrix.goarch }}
