name: Build Agents

on:
  push:
    branches: [master]
    paths:
      - "apps/agent/**"

jobs:
  build:
    name: Build Agent
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Build
        working-directory: apps/agent
        run: |
          mkdir -p dist/${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "darwin" ]; then
            CGO_ENABLED=1 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
              go build -o dist/${{ matrix.goos }}-${{ matrix.goarch }}/agent ./cmd/agent
          else
            CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
              go build -o dist/${{ matrix.goos }}-${{ matrix.goarch }}/agent ./cmd/agent
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-${{ matrix.goos }}-${{ matrix.goarch }}
          path: apps/agent/dist/${{ matrix.goos }}-${{ matrix.goarch }}
