name: Build Webextensions

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Webextensions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: apps/webextension
        run: npm ci

      - name: Build extension
        working-directory: apps/webextension
        run: npm run build:${{ matrix.browser }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-${{ matrix.browser }}
          path: apps/webextension/${{ matrix.browser }}
