name: Build Agents

on:
  push:
    branches: [master]
    paths:
      - "apps/agent/**"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Build Linux
        working-directory: apps/agent
        run: |
          mkdir -p dist/linux-${{ matrix.goarch }}
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o dist/linux-${{ matrix.goarch }}/agent ./cmd/agent
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.goarch }}
          path: |
            apps/agent/dist/linux-${{ matrix.goarch }}
            apps/agent/deploy/linux/*

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Build Windows
        working-directory: apps/agent
        shell: pwsh
        run: |
          mkdir -Force dist/windows-${{ matrix.goarch }}
          $env:GOOS="windows"
          $env:GOARCH="${{ matrix.goarch }}"
          go build -o dist/windows-${{ matrix.goarch }}/agent.exe ./cmd/agent
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.goarch }}
          path: |
            apps/agent/dist/windows-${{ matrix.goarch }}
            apps/agent/deploy/windows/*

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Build macOS
        working-directory: apps/agent
        run: |
          mkdir -p dist/darwin-${{ matrix.goarch }}
          GOOS=darwin GOARCH=${{ matrix.goarch }} go build -o dist/darwin-${{ matrix.goarch }}/agent ./cmd/agent
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-${{ matrix.goarch }}
          path: |
            apps/agent/dist/darwin-${{ matrix.goarch }}
            apps/agent/deploy/darwin/*
